-- Quizora product state. Additive only — this is live data from first deploy.
-- One row per Higgsfield user id (quiz_users.id). Question content itself is
-- NOT stored here — it ships as static JSON (app/src/data/questions.json),
-- generated by the validation script from the Google Sheet.

CREATE TABLE IF NOT EXISTS quiz_users (
  id TEXT PRIMARY KEY,               -- Higgsfield user id
  xp INTEGER NOT NULL DEFAULT 0,
  streak INTEGER NOT NULL DEFAULT 0,
  games_played INTEGER NOT NULL DEFAULT 0,
  daily_done TEXT,                   -- ISO date (YYYY-MM-DD) of last daily completion
  weekly_done TEXT,                  -- ISO week (YYYY-Www) of last weekly completion
  weekly_score INTEGER NOT NULL DEFAULT 0,
  weekly_perfect_bonus INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS quiz_history (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id TEXT NOT NULL REFERENCES quiz_users(id),
  played_at TEXT NOT NULL DEFAULT (datetime('now')),
  mode TEXT NOT NULL,                -- 'daily' | 'freeplay'
  category_label TEXT,               -- derived category label, freeplay only
  correct INTEGER NOT NULL,
  total INTEGER NOT NULL,
  score INTEGER NOT NULL,            -- normalized 0-100 for daily, raw points for freeplay
  perfect INTEGER NOT NULL DEFAULT 0,
  perfect_bonus INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_quiz_history_user ON quiz_history(user_id, played_at DESC);

CREATE TABLE IF NOT EXISTS quiz_weekly_history (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id TEXT NOT NULL REFERENCES quiz_users(id),
  week TEXT NOT NULL,                -- ISO week, e.g. 2026-W29
  played_at TEXT NOT NULL DEFAULT (datetime('now')),
  score INTEGER NOT NULL,
  perfect INTEGER NOT NULL DEFAULT 0,
  perfect_bonus INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_quiz_weekly_history_user ON quiz_weekly_history(user_id, played_at DESC);

-- No-repeat tracking, keyed by the question's stable id (not array index).
CREATE TABLE IF NOT EXISTS quiz_seen_questions (
  user_id TEXT NOT NULL REFERENCES quiz_users(id),
  question_id INTEGER NOT NULL,
  seen_at TEXT NOT NULL DEFAULT (datetime('now')),
  PRIMARY KEY (user_id, question_id)
);

-- Per top-level-tag play counts, backing the "Scientist" (5 plays of a given
-- top-level category) and "Explorer" (every top-level category played once)
-- badge predicates, which the reference build shipped as dead `() => false`.
CREATE TABLE IF NOT EXISTS quiz_category_plays (
  user_id TEXT NOT NULL REFERENCES quiz_users(id),
  top_level_tag TEXT NOT NULL,
  play_count INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (user_id, top_level_tag)
);

-- Badge labels already shown to the user as a popup, so we only toast on the
-- transition into "unlocked", not on every subsequent load.
CREATE TABLE IF NOT EXISTS quiz_badges_seen (
  user_id TEXT NOT NULL REFERENCES quiz_users(id),
  badge_id TEXT NOT NULL,
  seen_at TEXT NOT NULL DEFAULT (datetime('now')),
  PRIMARY KEY (user_id, badge_id)
);
